apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "patch-provider.fullname" . }}
  labels:
    {{- include "patch-provider.labels" . | nindent 4 }}
data:
  PATCH_PROVIDER_DEBUG: "{{ .Values.env.PATCH_PROVIDER_DEBUG }}"
  PATCH_PROVIDER_POLL_INTERVAL: {{ .Values.env.PATCH_PROVIDER_POLL_INTERVAL }}
