apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
  namespace: default
data:
  replicas: "3"
  value1: Foo1
  value2: Foo2
  value3: Foo3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bar
  namespace: default
data:
  value1: Bar1
  value2: Bar2