apiVersion: krateo.io/v1alpha1
kind: Patch
metadata:
  name: sample-jq
spec:
  from:
    objectReference:
      apiVersion: v1
      kind: ConfigMap
      name: foo
      # namespace: default
    fieldPath: data
  to:
    objectReference:
      apiVersion: apps/v1
      kind: Deployment
      name: nginx-deployment
      # namespace: default
    fieldPath: spec.replicas
    transform: ${ .replicas | tonumber }
 