name: Build stable Docker image (tags)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: Extract Version
      #   id: tagger
      #   uses: battila7/get-version-action@v2

      # - name: Print Version
      #   run: |
      #     echo ${{steps.tagger.outputs.version}}
      #     echo ${{steps.tagger.outputs.version-without-v}}
      - name: App Version
        uses: tdemin/find-latest-tag@v1
        id: app_version
        with:
          repo: https://${{ secrets.HELM_CHARTS_BOT }}@github.com/krateoplatformops/patch-provider.git
      - name: Print
        run: echo ${{ steps.app_version.outputs.tag }}
